<?php defined('ABSPATH') || exit; get_header(); ?>
<main id="main">
<section class="hero wrap">
<div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span><?php esc_html_e('MOVE DIFFERENTLY', 'shadowalker'); ?></p><h1><?php esc_html_e('Less ordinary.', 'shadowalker'); ?><br><em><?php esc_html_e('More electric.', 'shadowalker'); ?></em></h1><p class="hero-description"><?php esc_html_e('From the morning commute to the open water. Discover a new way to move, explore, and make it your own.', 'shadowalker'); ?></p><div class="hero-actions"><a class="button" href="<?php echo esc_url(sw_shop_url()); ?>"><?php esc_html_e('Find your ride', 'shadowalker'); ?> <span>↗</span></a><a class="text-link" href="#collections"><?php esc_html_e('Explore the collection', 'shadowalker'); ?> ↓</a></div><div class="hero-note"><span class="mini-orbit" aria-hidden="true">↗</span><p><?php esc_html_e('On land. On water.', 'shadowalker'); ?><br><strong><?php esc_html_e('On your terms.', 'shadowalker'); ?></strong></p></div></div>
<div class="hero-visual"><?php sw_art('landscape', __('An illustrated electric bike beside a lake and rolling hills', 'shadowalker')); ?><span class="visual-label">SHADOWALKER / OUTSIDE IS CALLING</span><div class="visual-caption"><span><?php esc_html_e('A new perspective', 'shadowalker'); ?><strong><?php esc_html_e('Starts with a little spark.', 'shadowalker'); ?></strong></span><a href="<?php echo esc_url(sw_category_url('electric-bikes')); ?>" aria-label="<?php esc_attr_e('Explore electric bikes', 'shadowalker'); ?>">↗</a></div></div>
</section>
<div class="principles wrap"><span>01 / <?php esc_html_e('Explore your possibilities', 'shadowalker'); ?></span><span>02 / <?php esc_html_e('Choose your own pace', 'shadowalker'); ?></span><span>03 / <?php esc_html_e('Make it electric', 'shadowalker'); ?></span></div>
<section class="section wrap" id="collections"><div class="section-heading"><div><p class="eyebrow"><?php esc_html_e('FOUR WAYS TO GO FURTHER', 'shadowalker'); ?></p><h2><?php esc_html_e('Where will you go?', 'shadowalker'); ?></h2></div><a class="text-link" href="<?php echo esc_url(sw_shop_url()); ?>"><?php esc_html_e('All products', 'shadowalker'); ?> ↗</a></div>
<div class="category-grid"><?php foreach (sw_categories() as $index => $category) { ?><a class="category-card category-<?php echo esc_attr($category[3]); ?>" href="<?php echo esc_url(sw_category_url($category[0])); ?>"><span class="category-number">0<?php echo (int) $index + 1; ?> /</span><?php sw_art($category[3], $category[1]); ?><div><h3><?php echo esc_html($category[1]); ?></h3><p><?php echo esc_html($category[2]); ?></p></div><span class="circle-arrow" aria-hidden="true">↗</span></a><?php } ?></div></section>
<section class="conversion wrap"><div class="conversion-art"><?php sw_art('kit', __('Illustrated electric bicycle conversion components', 'shadowalker')); ?><span class="round-label">RETHINK.<br>REBUILD.<br>RIDE.</span></div><div class="conversion-copy"><p class="eyebrow"><?php esc_html_e('SAME BIKE. NEW ENERGY.', 'shadowalker'); ?></p><h2><?php esc_html_e('Keep the bike.', 'shadowalker'); ?><br><em><?php esc_html_e('Change the journey.', 'shadowalker'); ?></em></h2><p><?php esc_html_e('Give a familiar ride a fresh start. Explore motors, batteries, controllers, and conversion kits. We can help you check compatibility before you choose.', 'shadowalker'); ?></p><a class="button" href="<?php echo esc_url(sw_category_url('conversion-kits')); ?>"><?php esc_html_e('Explore conversion kits', 'shadowalker'); ?> ↗</a></div></section>
<section class="section wrap"><div class="section-heading"><div><p class="eyebrow"><?php esc_html_e('MEET YOUR NEXT ADVENTURE', 'shadowalker'); ?></p><h2><?php esc_html_e('Ready for a different route.', 'shadowalker'); ?></h2></div><a class="text-link" href="<?php echo esc_url(sw_shop_url()); ?>"><?php esc_html_e('Browse the shop', 'shadowalker'); ?> ↗</a></div><?php if (class_exists('WooCommerce')) { echo do_shortcode('[products limit="4" columns="4" orderby="date" order="DESC" visibility="visible"]'); } else { ?><p><?php esc_html_e('Our collection is getting ready. Contact us to find your next ride.', 'shadowalker'); ?></p><?php } ?></section>
<section class="help-band wrap"><p class="eyebrow"><?php esc_html_e('LET’S FIND YOUR WAY', 'shadowalker'); ?></p><h2><?php esc_html_e('A fleet. A first ride.', 'shadowalker'); ?><br><?php esc_html_e('A project of your own.', 'shadowalker'); ?></h2><p><?php esc_html_e('Tell us what you have in mind. We’ll help you explore the options.', 'shadowalker'); ?></p><a class="button button-light" href="<?php echo esc_url(sw_page_url('contact')); ?>"><?php esc_html_e('Let’s talk', 'shadowalker'); ?> ↗</a><span class="giant-arrow" aria-hidden="true">↗</span></section>
</main><?php get_footer(); ?>
